 restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/guacamole:/config
    - ${DOCKERSHAREDDIR}:/shared
  letsencrypt:
    cap_add:
    - NET_ADMIN
    container_name: letsencrypt
    environment:
    - DNSPLUGIN=${LETSENCRYPT_DNSPLUGIN}
    - DUCKDNSTOKEN=${LETSENCRYPT_DUCKDNSTOKEN}
    - EMAIL=${LETSENCRYPT_EMAIL}
    - EXTRA_DOMAINS=${LETSENCRYPT_EXTRA_DOMAINS}
    - ONLY_SUBDOMAINS=${LETSENCRYPT_ONLY_SUBDOMAINS}
    - PGID=${PGID}
    - PUID=${PUID}
    - SUBDOMAINS=${LETSENCRYPT_SUBDOMAINS}
    - TZ=${TZ}
    - URL=${LETSENCRYPT_URL}
    - VALIDATION=${LETSENCRYPT_VALIDATION}
    hostname: ${DOCKERHOSTNAME}
    image: linuxserver/letsencrypt
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - ${LETSENCRYPT_PORT_443}:443
    - ${LETSENCRYPT_PORT_80}:80
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/letsencrypt:/config
    - ${DOCKERSHAREDDIR}:/shared
  ouroboros:
    container_name: ouroboros
    environment:
    - CLEANUP=${OUROBOROS_CLEANUP}
    - CRON=${OUROBOROS_CRON}
    - IGNORE=${OUROBOROS_IGNORE}
    - INTERVAL=${OUROBOROS_INTERVAL}
    - LOG_LEVEL=${OUROBOROS_LOG_LEVEL}
    - MONITOR=${OUROBOROS_MONITOR}
    - NOTIFIERS=${OUROBOROS_NOTIFIERS}
    - REPO_PASS=${OUROBOROS_REPO_PASS}
    - REPO_USER=${OUROBOROS_REPO_USER}
    - SELF_UPDATE=${OUROBOROS_SELF_UPDATE}
    - TZ=${TZ}
    hostname: ${DOCKERHOSTNAME}
    image: pyouroboros/ouroboros
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - ${DOCKERSHAREDDIR}:/shared
  portainer:
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    environment:
    - TZ=${TZ}
    hostname: ${DOCKERHOSTNAME}
    image: portainer/portainer
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - ${PORTAINER_PORT_9000}:9000
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - ${DOCKERCONFDIR}/portainer:/data
    - ${DOCKERSHAREDDIR}:/shared
version: "3.4"
